- name: Create CentOS-7 Compute Instance
  hosts: localhost
  gather_facts: no

  vars:
    gcp_project: "PROJECT_ID"
    gcp_cred_file: "PATH_TO_CREDENTIAL_FILE"
    gcp_cred_kind: "serviceaccount"
    gcp_region: "REGION"
    gcp_zone: "ZONE"
    scopes:
      - https://www.googleapis.com/auth/compute
  
  tasks:

    - name: Create a disk
      google.cloud.gcp_compute_disk:
        name: mysql-server-disk
        size_gb: 200
        source_image: projects/centos-cloud/global/images/family/centos-7
        zone: "{{ gcp_region }}-{{ gcp_zone }}"
        project:  "{{ gcp_project }}"
        auth_kind:  "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: present
      register: disk

    - name: Create a address
      google.cloud.gcp_compute_address:
        name: mysql-server-address
        region: "{{ gcp_region }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: present
      register: address

    - name: Create a instance with CentOS-7
      google.cloud.gcp_compute_instance:
        name: mysql-server-centos7
        machine_type: c2-standard-8
        disks:
          - boot: 'true'
            source: "{{ disk }}"
            type: PERSISTENT
        metadata:
          startup-script: 'yum install https://dev.mysql.com/get/mysql80-community-release-el7-3.noarch.rpm -y
            && yum install mysql-server -y'
        labels:
          environment: production
        network_interfaces:
        - access_configs:
          - name: External NAT
            nat_ip: "{{ address }}"
            type: ONE_TO_ONE_NAT
        tags:
          items:
          - mysql-server-centos7
        zone: "{{ gcp_region }}-{{ gcp_zone }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
        state: present
        scopes:
           - https://www.googleapis.com/auth/compute
      register: instance

    - name: Wait for SSH to come up
      wait_for: host={{ address.address }} port=22 delay=10 timeout=60

    - name: Add host to groupname
      add_host: hostname={{ address.address }} groupname=mysql_server

    - name: Show IP Address Of MySQL Server
      set_fact:
        ansible_ssh_host: "{{ address.address }}"
    - debug:
        msg: "ssh $USER@{{ ansible_ssh_host }}"